### ISSUE TITLE
IPv6 : The firewall should drop input requests by default

### ISSUE THREAD

**Issue by olethanh** [labriqueinternet/hotspot_ynh#12]
Or even be disabled by default. This is a small security risk because it expose computers on the internet without it's users being aware of it so he may not have sufficiently secured them.

**Comment by jvaubourg** [comment]
IPv6 is NOT less secure than IPv4.

Please, do not confuse NAT-PT and firewalling. Having a public address for each client is juste the natural way to do networks. Using NAT-PT everywhere is an aberration ONLY due to the IPv4 address exhaustion. Disabling IPv6 by default is something stupid because we need to encourage the IPv6 spreading. Without IPv6 in the future, self-hosting and net neutrality will no longer be possible. If you understand French, you can see [this talk](http://ldn-fai.net/intranet-ipv4-ou-internet-ipv6/).

But, you are right : the firewall of the Hotspot App should drop input requests by default. We need to change that, thank you.

(BTW if you do not set the IPv6 delegated prefix in the web admin of the Hotspot App, clients will not receive an IPv6 address)

**Comment by olethanh** [comment]
> IPv6 is NOT less secure than IPv4.

I never said that and I certainly don't believe it.

I totally agree that relying on NAT for security is bad and not how networking should be done, but people have become reliant on it to separate private and public services so this separation shouldn't be dropped by default until users  get new reflexes ;)

> But, you are right : the firewall of the Hotspot App should drop input requests by default. We need to change that, thank you.

That seems like a good fix to me.

> (BTW if you do not set the IPv6 delegated prefix in the web admin of the Hotspot App, clients will not receive an IPv6 address)

Good I didn't know that.

**Comment by jvaubourg** [comment]
You now have a switch button for each SSID, for enabling or disabling a firewall. This one drops any IPv6 input connections to the clients.

**Comment by olethanh** [comment]
Thanks a lot
