### ISSUE TITLE
Installationerror - dnsmasq instead of bind9

### ISSUE THREAD

**Issue by finster-** [labriqueinternet/hotspot_ynh#21]
When i try to install the hotspot i get the following error:

```
+ domain=xxx.xxx.xx
+ url_path=/wifiadmin
+ wifi_ssid=myNeutralNetwork
+ wifi_passphrase=test123456
+ firmware_nonfree=yes
++ grep ii
++ awk '{ print $3 }'
++ sudo dpkg -l yunohost
++ sed 's/\.//g'
+ ynh_version=220
+ '[' 220 -lt 220 ']'
+ sudo systemctl is-active dnsmasq
+ '[' 1 -ne 0 ']'
+ echo 'ERROR: You need to enable dnsmasq instead of bind9 (apt-get remove bind9 && systemctl start dnsmasq)'
ERROR: You need to enable dnsmasq instead of bind9 (apt-get remove bind9 && systemctl start dnsmasq)
+ exit 1
```

**Comment by sbadia** [comment]
hi @finster- please provide us a bit more informations…
`hotspot_ynh` is compatible with `yunhost` 2.x and with debian jessie images. Can you give us more information about your environment?

**Comment by finster-** [comment]
I'm running Debian wheezy on a banana-pi...that may be the problem. 
Didn't see the prerequisites, sorry about that.
I just realised that there is no 'systemctl' in wheezy but i could install it. Would that help or ?

**Comment by sbadia** [comment]
Arf, it seems that the stable image for Banana-pi is still using old-stable Debian version (eg. wheezy), you can try to install `systemd` and compat. mode `systemd-sysv` but without guaranties :-s

Otherwise, it seems that you board (the banana-pi) run a A20 Soc http://www.bananapi.org/p/product.html, it's exactly the same hardware than our olimex images, you can maybe tries the labriqueinternet images here ? https://repo.labriqueinter.net/ (please see a detailed howto on the yunohost website https://yunohost.org/#/installation_brique_fr )

Keep us informed :-)

**Comment by finster-** [comment]
Will try the labriqueinternet image later today. Had already a look  at it but was not sure is it is compatible with the banana-pi

**Comment by finster-** [comment]
Cant get the image running. The system gets stuck when i try to do anything and nothing happens anymore.
I will try the jessie image with yunohost. Thought about building a image myself but the stepts at https://github.com/labriqueinternet/build.labriqueinter.net/ use sunxi-debian and i dont know if that works for me...

**Comment by jvaubourg** [comment]
I think this bug can be closed (the potential issues with the Debian image are not Hotspot related).
